#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_qt_gui/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import rqt_gui.main
import sys

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    main = rqt_gui.main.Main()
    sys.exit(main.main(sys.argv, standalone='rocon_remocon'))
