#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_qt_gui/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import sys
import os
import signal

import rospkg

from python_qt_binding.QtGui import QApplication, QIcon  # QAction, QFrame, QIcon,QMainWindow, QMenu, QSystemTrayIcon
from python_qt_binding.QtCore import QTimer  # Qt

import rocon_remocon

##############################################################################
# Globals
##############################################################################.

app = None
myapp = None

##############################################################################
# Methods
##############################################################################.


def signal_handler(signum, f):
    print "[main] Interrupt"
    if signum == signal.SIGINT:
        app.exit(0)

##############################################################################
# Main
##############################################################################.


if __name__ == "__main__":
    
    rospack = rospkg.RosPack()
    icon_file = os.path.join(rospack.get_path('rocon_icons'), 'icons', 'rocon_logo.png')
    
    signal.signal(signal.SIGINT, signal_handler)
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon(icon_file))
    # Let the interpreter run each 200 ms.
    timer = QTimer()
    timer.start(200)
    timer.timeout.connect(lambda: None)
    myapp = rocon_remocon.QMasterChooser(None, "Rocon Remocon", app)
    app.exec_()
    print "rocon_remocon: Main end"
